language: node_js
cache: npm
os: osx
node_js:
  - "8"
install:
  - cd native/electron
  - npm i
  - cd ../../scripts
  - npm i
  - cd ..
script:
  - cd scripts
  - npm run build
  - cd ../native/electron
  - npm run build
  - npm run package:mac