language: node_js
cache: npm
node_js:
- '8'
matrix:
  include:
  - os: osx
    install:
    - cd native/electron
    - npm i
    - cd ../../scripts
    - npm i
    - cd ..
    script:
    - cd scripts
    - npm run build
    - cd ../native/electron
    - npm run build
    - npm run package:mac
    - cd ../..
  - os: windows
    install:
    - cd native/electron
    - npm i
    - cd ../../scripts
    - npm i
    - cd ..
    script:
    - cd scripts
    - npm run build
    - cd ../native/electron
    - npm run build
    - npm run package:windows
    - cd ../..
deploy:
  provider: releases
  api_key:
    secure: pEZ5VA8ZAbvp+LtS6zXp+SMPqUKhhctg9TlATrMJ1TFztnqnEw0KwuQomQPlI9/6YAVan+HZIBcgoHkOOmZcRpREs/tT0ccHlhQEEVPApwIqFtRJc2+1cT0ZZJen63H5005R+KifcOspNCpdfIdxdCEl+q0s1fLInLsQ5JFsUFKnYK1Y6PzPYPf4H6IERqoWNVlGRc79ivO6F0h9lO6CFgZDnXbiyViQRI/jxIxnLleNdTtaOQ6PoHhWCrNiTYbSWcWywAxru/LZ6lyQS8S/suYL4ZBNkTgAuPDqxR4ChWcR19QVLRkM5UUtdxAdRDDOVvPD+ResmJFNadz7BzWbaFM/cZq5oysgUCLJ1Bliwi8GOGfepu+8wXrcJkh3uXmcMlt7Y/uxwvZ/Cpm3X0chLn0tn9D+cEGPpbDMPzEhqOH7BaZdKra5MmtVru1H8EPqWjIBTI4HSC4vQyCemFeTJMrOMo/5tXi8W8xXisLt8GGB0Ko3wIiJfiDIwK6SlGl8I8sT5TJsp44LaT/D2inMWERVMPsdoJH2UWC6hvSLE3RamoGZJP7/mWAZW3OS6RcaUlSpbc3wl0+/4dIyNTPya8r4mPTaJ0KyMRVP/fGNg656OhQ1KETSI2zia/uRV71TrIdGUhOoN+vTwpxdMPUlHRv6MVzQdFsoVajmUXQqIhw=
  file_glob: true
  skip_cleanup: true
  file: native/electron/packaged/*
  on:
    repo: langyo/MCBBS-Client
    branch: master
    tags: true
